### ISSUE TITLE
Issue to update to 2.0

### ISSUE THREAD

**Issue by khzd** [lcmchris/thesillyhome-addon-repo#7]
Hi 
I got this error trying to update my 1.0.2 release
Can't install 89141162/amd64-addon-thesillyhome:2.0.0: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=2.0.0&fromImage=89141162%2Famd64-addon-thesillyhome&platform=linux%2Famd64: Not Found ("pull access denied for 89141162/amd64-addon-thesillyhome, repository does not exist or may require 'docker login': denied: requested access to the resource is denied")

Any advise ?
Thanks for this great add on

**Comment by lcmchris** [comment]
Thanks for raising this. I have been building solely on my windows machine and unfortunately have neglected the fact that the pi runs on a different architecture ... 
Am currently fixing the image such that it works with both. Please bear with me (as building py pacakges on armv7/v8 is wickedly slow :(

**Comment by lcmchris** [comment]
Hi @khzd 
I've made a fix and it should now be working. Please check for updates on HA Addon and then the version should be 2.0.1 
Please check https://github.com/lcmchris/thesillyhome-container/commit/e4d865fc06e23c8b2ffe6a31f28a8267e9c034d1 for code change details!

**Comment by lcmchris** [comment]
Will close for now. Please re-open if you see issues again.
